### ISSUE TITLE
Where is data coming from?

### ISSUE THREAD

**Issue by tankerkiller125** [judge2020/Actual-Domain-Prices#2]
I'm trying to figure out where your getting this data, I've spent a lot of time on their site trying to find the real prices with no success, I would love to know how you're getting this prices.

**Comment by judge2020** [comment]
The data comes from a bug in Cloudflare's API. We're able to ask it "what is the price to transfer domain.tld" even if the domain we ask for isn't in our account (their system verified you own the domain later in the process). Doing this, I can send every single TLD to the API and get all of the prices back.


The code I hacked up a while ago that does this - 
https://github.com/judge2020/CloudDump

**Comment by AnimMouse** [comment]
Hopefully Cloudflare will not "patch" the bug.

**Comment by tankerkiller125** [comment]
@AnimMouse It seems that Cloudflare is perfectly fine with this bug existing, I've seen several of their support staff links directly to this repo. It seems that they themselves are not allowed to disclose the information in public but someone else doing so via a "broken" API is perfectly fine. I think Cloudflare may be using this as a workaround to their legal requirements.

**Comment by AnimMouse** [comment]
@tankerkiller125 That is a nice legal loophole down there!
